
<?= $this->getContent() ?>
<?php
    if($errorMessage) {
        echo '<div class="alert alert-danger" role="alert">' . $errorMessage . '</div>';
    }
?>


<form class="login" method="post">
    <div class="form-group">
<!--    <label class="col-form-label" for="formGroupExampleInput">Логин</label>-->
    <input type="text" name="login" class="form-control" id="formGroupExampleInput" placeholder="введите логин...">
    </div>
    <div class="form-group">
<!--    <label class="col-form-label" for="formGroupExampleInput2">Пароль</label>-->
    <input type="password" name="password" class="form-control" id="formGroupExampleInput2" placeholder="введите пароль...">

    </div>
    <input type="submit" class="btn btn-primary" value="Вход">
</form>