<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Административная часть сайта</title>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="/css/admin.css">
    <link rel="stylesheet" href="/css/responsive.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>

<div class="container">
<?php if ($menu) : ?>
    <a href="/admin/auth/logout" class="link-button -logout">Выйти</a>
    <nav class="navbar navbar-expand-lg  nav-pills nav-justified bg-light ">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<!--            <span class="navbar-toggler-icon"></span>-->
            <a class="navbar-brand" href="#">Меню</a>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
<!--                    <a class="nav-link --><?//=$mainActive ?><!--" href="/admin/">Главная</a>-->
                </li>
                <li class="nav-item ">
                    <a class="nav-link <?= $statementActive ?>" href="/admin/statements">Выписки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin/houses">Дома</a>
                </li>
            </ul>
        </div>

    </nav>

<?php endif; ?>

<?php echo $this->getContent(); ?>
<div class="pre-footer"></div>
</div>
<footer>
    <div class="container">
        <div class="footer-content"><span>&copy; 2009 – <?= date('Y') ?> Управляющая организация «РСУ 7» </span></div>
    </div>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>-->
<!-- Latest compiled and minified JavaScript -->
<!--        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<script src="/js/admin.js"></script>
</body>
</html>